### ISSUE TITLE
Full width

### ISSUE THREAD

**Issue by RWOverdijk** [expo/react-native-responsive-image#1]
This is probably outside of the scope of this repository... But I still wanted to ask.

How should one deal with full-width images? I mean, density and resolution are two different beasts. Should the largest resolution be used to create the images? Or is there a detection technique?

Thanks in advance.

**Comment by ide** [comment]
We could eventually explore this but haven't looked into it because picking the right resolution is more ambiguous than picking the best density. Maybe we could learn from the `srcSet` attribute and `<picture>` element.

For now my recommendation is to write this logic yourself. The nice thing is with RN, everything is in JS which is much easier than media queries and CSS, so you can describe whatever behavior you want.

Another thing I've found to be super useful is to have a image server that can resize images on the fly. We have URLs like `http://cdn.example.com/resize;width=250;height=75/encode;quality=85/image.png`. The client generates the URLs that are best for the user's device and the server does the work of sending back the appropriate image.

**Comment by RWOverdijk** [comment]
@ide Thanks! I'll just use the Dimensions lib (found it [here](https://github.com/GertjanReynaert/react-native-device/blob/master/Device.js#L8,L9)) to decide if I want to use image-lg or image.

As to the cdn, I already do that. I just like to have presets to preserve disk space for now, so I try to not use it haha.

Thank you again :)

**Update**:
In case anyone ever finds this issue and the code I liked to has moved, you can use:

``` javascript
var { Dimensions } = require('react-native'),
    width          = Dimensions.get('window').width,
    height         = Dimensions.get('window').height;
```

**Comment by ide** [comment]
BTW you should require Dimensions via react-native: `var { Dimensions } = require('react-native');`.

**Comment by RWOverdijk** [comment]
@ide Why? (just curious)

PS: Also updated my comment above to reflect what you just said

**Comment by ide** [comment]
The fact that you can write `require('Dimensions')` and have it reach into react-native is a bug and non-standard behavior so the packager may break it at any time.

**Comment by RWOverdijk** [comment]
Noted. I'll submit a PR to the module I got it from, too. Thanks again :)
